// Scene graph builders.
// Each export returns a plain-data Scene Graph v1 object that the renderer
// can consume.  No Three.js imports here — scenes are pure data so they can
// be serialised, validated, or eventually generated by an LLM.

export function createImpactSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 10,
        world: {
            environment: 'space',
            timeScale: 1,
            physicsMode: 'plausible'
        },
        objects: [
            {
                id: 'earth',
                type: 'sphere',
                role: 'planet',
                position: [0, 0, 0],
                radius: 12,
                material: {
                    preset: 'earthlike',
                    color: palette[0],
                    atmosphere: true
                }
            },
            {
                id: 'comet',
                type: 'projectile',
                role: 'comet',
                radius: 1.25,
                start: [52, 25, -48],
                end: [8.8, 5.6, -6.4],
                impactAt: 4.2,
                material: {
                    preset: 'ice_glow',
                    color: '#dff7ff'
                },
                trail: {
                    enabled: true,
                    length: 42,
                    color: palette[2] || '#ffb454'
                }
            }
        ],
        events: [
            {
                id: 'impact',
                type: 'collision',
                source: 'comet',
                target: 'earth',
                at: 4.2,
                position: [8.8, 5.6, -6.4],
                effects: ['flash', 'shockwave', 'debris']
            }
        ],
        effects: [
            { id: 'flash', type: 'flash', event: 'impact', color: palette[2] || '#ffb454', duration: 0.85 },
            { id: 'shockwave', type: 'shockwave', event: 'impact', color: palette[2] || '#ffb454', duration: 3.4, maxRadius: 24 },
            { id: 'debris', type: 'debris', event: 'impact', color: palette[3] || '#ff5b45', count: 480 }
        ],
        camera: {
            mode: 'cinematic_orbit',
            focus: 'earth',
            distance: 58,
            shakeAt: 4.2
        },
        seed
    };
}

// --- Binary star: FIXED ----------------------------------------------------
//
// Previous version used two fuzzy `particle_cloud` blobs plus a vertical
// sinusoid on the orbit, which made it look like wandering smoke. New
// version uses dedicated `star_body` objects (dense Fibonacci core + soft
// corona) and a proper `binary_orbit` motion that keeps both stars in a
// shared plane around the barycenter at [0, 0, 0].
export function createBinaryStarSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 14,
        world: { environment: 'space', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'star_a',
                type: 'star_body',
                role: 'star',
                radius: 4.6,
                massRatio: 1.0,
                material: {
                    color: palette[0] || '#ffcf6b',
                    corona: '#ffe3a3',
                    coronaRadius: 9.5
                }
            },
            {
                id: 'star_b',
                type: 'star_body',
                role: 'star',
                radius: 3.4,
                massRatio: 1.6, // star B is lighter ⇒ sits farther from barycenter
                material: {
                    color: palette[1] || '#78a6ff',
                    corona: '#c6dcff',
                    coronaRadius: 7.5
                }
            },
            {
                id: 'barycenter_mark',
                type: 'glow_point',
                role: 'barycenter',
                radius: 0.5,
                material: { color: palette[2] || '#f5f7fb' }
            }
        ],
        motions: [
            {
                type: 'binary_orbit',
                targets: ['star_a', 'star_b'],
                semiMajor: 18,
                speed: 0.52,
                tilt: 0.12
            }
        ],
        forces: [],
        effects: [
            { id: 'starfield', type: 'starfield', count: 600, color: '#f5f7fb', radius: 80 }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 62 },
        seed
    };
}

export function createMagneticFieldSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 12,
        world: { environment: 'field', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'field_lines',
                type: 'field_lines',
                role: 'magnetic_field',
                position: [0, 0, 0],
                lineCount: 18,
                pointsPerLine: 90,
                radius: 26,
                material: { color: palette[0] || '#45d7ff' }
            },
            {
                id: 'charge_flow',
                type: 'particle_cloud',
                role: 'charged_flow',
                position: [0, 0, 0],
                radius: 20,
                particleCount: 1600,
                material: { color: palette[1] || '#ff5b8a' }
            }
        ],
        motions: [
            { type: 'helix_flow', target: 'charge_flow', speed: 0.9, radius: 18 }
        ],
        forces: [
            { type: 'magnetic', target: 'charge_flow', strength: 1.1, axis: [0, 1, 0] }
        ],
        effects: [
            { id: 'axis_core', type: 'glow_core', color: palette[3] || '#20d6b5', radius: 1.8 }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 70 },
        seed
    };
}

export function createSolarSystemSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 18,
        world: { environment: 'space', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            { id: 'sun', type: 'star_body', role: 'sun', radius: 5.6, material: { color: palette[0] || '#ffcf6b', corona: '#ffe3a3', coronaRadius: 11 } },
            { id: 'planet_inner', type: 'particle_cloud', role: 'planet', position: [14, 0, 0], radius: 1.5, particleCount: 320, material: { color: palette[2] || '#ff8a4a' } },
            { id: 'earth', type: 'sphere', role: 'planet', position: [25, 0, 0], radius: 2.2, material: { preset: 'earthlike', color: palette[1] || '#2e7cff', atmosphere: true } },
            { id: 'planet_outer', type: 'particle_cloud', role: 'planet', position: [38, 0, 0], radius: 2.8, particleCount: 520, material: { color: palette[3] || '#d9d7c8' } },
            { id: 'moon', type: 'particle_cloud', role: 'moon', position: [29, 0, 0], radius: 0.7, particleCount: 180, material: { color: '#d9d7c8' } }
        ],
        motions: [
            { type: 'orbit_body', target: 'planet_inner', center: 'sun', radius: 14, speed: 1.1, tilt: 0.04 },
            { type: 'orbit_body', target: 'earth', center: 'sun', radius: 25, speed: 0.72, tilt: 0.08 },
            { type: 'orbit_body', target: 'planet_outer', center: 'sun', radius: 38, speed: 0.42, tilt: 0.12 },
            { type: 'orbit_body', target: 'moon', center: 'earth', radius: 4.4, speed: 2.4, tilt: 0.25 }
        ],
        forces: [
            { type: 'gravity_well', target: 'sun', strength: 0.5 }
        ],
        effects: [
            { id: 'orbit_rings', type: 'orbit_rings', targets: ['planet_inner', 'earth', 'planet_outer'], color: '#f5f7fb' }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 82 },
        seed
    };
}

export function createEarthMoonSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 14,
        world: { environment: 'space', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'earth',
                type: 'sphere',
                role: 'planet',
                position: [0, 0, 0],
                radius: 8,
                material: { preset: 'earthlike', color: palette[0] || '#2e7cff', atmosphere: true }
            },
            {
                id: 'moon',
                type: 'particle_cloud',
                role: 'moon',
                position: [18, 0, 0],
                radius: 1.8,
                particleCount: 520,
                material: { color: palette[1] || '#d9d7c8' }
            }
        ],
        motions: [
            { type: 'orbit_body', target: 'moon', center: 'earth', radius: 19, speed: 0.92, tilt: 0.22 }
        ],
        forces: [],
        effects: [
            { id: 'moon_orbit', type: 'orbit_rings', targets: ['moon'], color: palette[2] || '#62d7ff' }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 52 },
        seed
    };
}

// --- Speeding car: FIXED ---------------------------------------------------
//
// Previous version baked body + glass + lights + 4 wheels into a single
// Points buffer, so the wheels couldn't actually rotate. New version splits
// each part into its own object and attaches `spin` motions to the wheels —
// chassis and cabin remain static while wheels rotate around their local Z.
export function createSpeedingCarSceneGraph(seed, palette, dense = false) {
    const wheelOffset = 4.45;
    const wheelY = -0.85;
    const wheelRadius = 1.55;
    const wheelCount = dense ? 360 : 240;
    const spinSpeed = 8;

    const wheels = [
        { id: 'wheel_fl', position: [-8, wheelY, -wheelOffset] },
        { id: 'wheel_fr', position: [-8, wheelY,  wheelOffset] },
        { id: 'wheel_rl', position: [ 8, wheelY, -wheelOffset] },
        { id: 'wheel_rr', position: [ 8, wheelY,  wheelOffset] }
    ];

    return {
        version: 1,
        duration: 12,
        world: { environment: 'highway', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'car_chassis',
                type: 'car_part',
                preset: 'chassis',
                role: 'vehicle',
                position: [0, -1.5, 0],
                particleCount: dense ? 2600 : 2000,
                material: { color: palette[0] || '#4fd8ff' }
            },
            {
                id: 'car_cabin',
                type: 'car_part',
                preset: 'cabin',
                position: [-2.4, 3.6, 0],
                particleCount: dense ? 900 : 700,
                material: { color: '#d9f6ff' }
            },
            {
                id: 'car_front_light',
                type: 'car_part',
                preset: 'front_light',
                position: [12.2, 0.7, 0],
                particleCount: 160,
                material: { color: palette[2] || '#ffcf6b' }
            },
            {
                id: 'car_tail_light',
                type: 'car_part',
                preset: 'tail_light',
                position: [-13.2, 0.5, 0],
                particleCount: 160,
                material: { color: palette[3] || '#ff4f6d' }
            },
            ...wheels.map((w) => ({
                id: w.id,
                type: 'wheel',
                role: 'wheel',
                position: [w.position[0], w.position[1] - 1.5, w.position[2]],
                radius: wheelRadius,
                particleCount: wheelCount,
                material: { tyre: '#1a1d22', rim: '#9aa6b8', spokes: '#f5f7fb' }
            })),
            {
                id: 'highway',
                type: 'particle_shape',
                preset: 'highway',
                role: 'road',
                position: [0, -7, 0],
                particleCount: dense ? 1700 : 1200,
                material: {
                    asphalt: '#384150',
                    lane: '#f5f7fb',
                    edge: '#45d7ff'
                }
            }
        ],
        motions: [
            { type: 'speed_pulse', target: 'car_chassis', amplitude: 0.16, speed: 5.2 },
            { type: 'speed_pulse', target: 'car_cabin', amplitude: 0.16, speed: 5.2 },
            ...wheels.map((w) => ({
                type: 'spin',
                target: w.id,
                axis: 'z',
                speed: spinSpeed
            })),
            ...wheels.map((w) => ({
                type: 'speed_pulse',
                target: w.id,
                amplitude: 0.12,
                speed: 5.2
            })),
            { type: 'road_scroll', target: 'highway', speed: 1.15, length: 86 }
        ],
        forces: [],
        effects: [
            {
                id: 'speed_wake',
                type: 'speed_trail',
                target: 'car_chassis',
                color: palette[1] || '#f5f7fb',
                count: dense ? 900 : 620,
                length: 38
            }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 44 },
        seed
    };
}

export function createAttractionSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 12,
        world: { environment: 'space', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'orb_a',
                type: 'particle_cloud',
                role: 'attractor',
                position: [-20, 3, 0],
                radius: 6,
                particleCount: 1400,
                material: { color: palette[0] || '#b48cff' }
            },
            {
                id: 'orb_b',
                type: 'particle_cloud',
                role: 'attractor',
                position: [20, -3, 0],
                radius: 6,
                particleCount: 1400,
                material: { color: palette[1] || '#20d6b5' }
            }
        ],
        motions: [
            { type: 'orbit', targets: ['orb_a', 'orb_b'], radius: 20, speed: 0.55 }
        ],
        forces: [
            { type: 'attraction', targets: ['orb_a', 'orb_b'], strength: 0.72, spiral: 0.58 }
        ],
        effects: [
            { id: 'bridge', type: 'particle_bridge', targets: ['orb_a', 'orb_b'], color: palette[2] || '#f2e7ff', count: 900 }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 64 },
        seed
    };
}

export function createVortexSceneGraph(seed, palette) {
    return {
        version: 1,
        duration: 12,
        world: { environment: 'space', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'vortex_cloud',
                type: 'particle_cloud',
                role: 'flow',
                position: [0, 0, 0],
                radius: 28,
                particleCount: 4200,
                material: { color: palette[0] || '#b48cff' }
            }
        ],
        motions: [
            { type: 'spiral', target: 'vortex_cloud', speed: 0.95, inward: 0.32 }
        ],
        forces: [
            { type: 'vortex', target: 'vortex_cloud', strength: 1, center: [0, 0, 0] }
        ],
        effects: [
            { id: 'core', type: 'glow_core', color: palette[1] || '#45d7ff', radius: 3.5 }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 72 },
        seed
    };
}

// --- Text scene: NEW -------------------------------------------------------
//
// Renders a string as a glowing particle field. The renderer rasterises
// the text into a hidden canvas, samples bright pixels, then assigns each
// to a Three.js Points vertex.
export function createTextSceneGraph(seed, palette, text, { dense, bright } = {}) {
    return {
        version: 1,
        duration: 12,
        world: { environment: 'studio', timeScale: 1, physicsMode: 'plausible' },
        objects: [
            {
                id: 'caption',
                type: 'text_particles',
                role: 'text',
                text,
                font: 'bold 220px Inter, "Segoe UI", system-ui, sans-serif',
                particleCount: dense ? 6000 : 4000,
                material: {
                    color: palette[0] || '#20d6b5',
                    accent: palette[1] || '#6aa9ff'
                }
            }
        ],
        motions: [
            { type: 'float', target: 'caption', amplitude: 0.5, speed: 0.6 }
        ],
        forces: [],
        effects: [
            { id: 'caption_glow', type: 'glow_core', color: palette[1] || '#6aa9ff', radius: 1.2, attachedTo: 'caption' }
        ],
        events: [],
        camera: { mode: 'free_orbit', distance: 58 },
        seed
    };
}
